### ISSUE TITLE
Can't change label colors

### ISSUE THREAD

**Issue by Nik99** [google/charts#124]
Hi everyone. I'm trying to change the default text color from black to white, but everytime i use the ArcLabelDecorator on my pie chart, it says this: 

> |flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown during paint():
flutter: The method '/' was called on null.
flutter: Receiver: null
flutter: Tried calling: /(2)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
flutter: #1      ArcLabelDecorator._drawOutsideLabel (package:charts_common/src/chart/pie/arc_label_decorator.dart:282:67)
flutter: #2      ArcLabelDecorator.decorate (package:charts_common/src/chart/pie/arc_label_decorator.dart:197:21)
flutter: #3      ArcRenderer.paint.<anonymous closure>.<anonymous closure> (package:charts_common/src/chart/pie/arc_renderer.dart:374:19)
flutter: #4      Iterable.forEach (dart:core/iterable.dart:277:30)
flutter: #5      ArcRenderer.paint.<anonymous closure> (package:charts_common/src/chart/pie/arc_renderer.dart:373:12)
flutter: #6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:365:8)
flutter: #7      ArcRenderer.paint (package:charts_common/src/chart/pie/arc_renderer.dart:332:19)
flutter: #8      BaseChart.paint.<anonymous closure> (package:charts_common/src/chart/common/base_chart.dart:527:12)
flutter: #9      List.forEach (dart:core/runtime/libgrowable_array.dart:275:8)
flutter: #10     BaseChart.paint (package:charts_common/src/chart/common/base_chart.dart:525:38)
flutter: #11     ChartContainerCustomPaint.paint (package:charts_flutter/src/chart_container.dart:339:11)
flutter: #12     RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:520:13)
flutter: #13     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:558:7)
flutter: #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
flutter: #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
flutter: #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #22     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2267:15)
flutter: #23     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:360:5)
flutter: #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #25     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #26     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #27     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
flutter: #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #32     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #35     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2267:15)
flutter: #36     RenderFlex.paint (package:flutter/src/rendering/flex.dart:931:7)
flutter: #37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #39     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
flutter: #43     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:472:11)
flutter: #44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:126:15)
flutter: #47     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:1709:88)
flutter: #48     ClipContext._clipAndPaint (package:flutter/src/painting/clip.dart:29:12)
flutter: #49     ClipContext.clipRRectAndPaint (package:flutter/src/painting/clip.dart:49:5)
flutter: #50     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1709:17)
flutter: #51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #52     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #53     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2267:15)
flutter: #54     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:604:5)
flutter: #55     RenderStack.paint (package:flutter/src/rendering/stack.dart:612:7)
flutter: #56     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #57     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #58     RenderSliverSingleBoxAdapter.paint (package:flutter/src/rendering/sliver.dart:1586:15)
flutter: #59     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #60     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:131:13)
flutter: #61     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:524:17)
flutter: #62     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:305:12)
flutter: #63     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:323:7)
flutter: #64     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:515:15)
flutter: #65     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2017:7)
flutter: #66     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:111:11)
flutter: #67     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:784:29)
flutter: #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:272:19)
flutter: #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
flutter: #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
flutter: #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
flutter: #75     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #76     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #77     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   ChartContainerRenderObject<dynamic>#3e9cc
flutter:   creator: ChartContainer<dynamic> ← Listener ← _GestureSemantics ← RawGestureDetector ←
flutter:   GestureDetector ← LayoutId-[<chartContainer>] ← CustomMultiChildLayout ← PieChart<dynamic> ←
flutter:   DettaglioPiattoGraficoDichiarazioneNutrizionale ← Padding ← ConstrainedBox ← Container ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=359.0, h=234.0)
flutter:   semantics node: SemanticsNode#161
flutter:   semantic boundary
flutter:   size: Size(359.0, 234.0)
flutter: This RenderObject has no descendants.
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The method '/' was called on null.

This is my code 
`defaultRenderer: new charts.ArcRendererConfig(
        strokeWidthPx: 2.0,
        arcRendererDecorators: [
          new charts.ArcLabelDecorator(
            labelPosition: charts.ArcLabelPosition.auto,
            labelPadding: 3,
            showLeaderLines: true,
            outsideLabelStyleSpec: charts.TextStyleSpec(
              color: charts.Color.white,
            ),
          ),
        ],
      ),`

**Comment by Nik99** [comment]
it seems to be happening for everything related to TextStyleSpec

**Comment by JamesMcIntosh** [comment]
If you dig into the source of the exception you will see that a fontSize is required for the outsideLabelStyleSpec. i.e.

```
outsideLabelStyleSpec: charts.TextStyleSpec(
  color: charts.Color.white,
  fontSize: 12,
)
```

I'm not sure if this is a bug, by design or missing documentation without going deeper into the code.
