### ISSUE TITLE
OrdinalComboChart throws exception in release mode

### ISSUE THREAD

**Issue by TomOerlemans** [google/charts#177]
I noticed an issue with OrdinalComboChart when deploying in release mode (the issue does to happen in debug mode). I am displaying the chart on the first 'page' that is loaded when the app is opened, and the issue resolves itself when I navigate to another widget and then back.

This is the code I am using to build the chart widget.

`return Container(
      height: 205.0,
      width: 350.0,
      child: new charts.OrdinalComboChart(seriesList,
          animate: animate,
          // Configure the default renderer as a bar renderer.
          defaultRenderer: charts.LineRendererConfig(
            includeArea: true,
            stacked: true,
            areaOpacity: 0.8,
          ),
          // Custom renderer configuration for the line series. This will be used for
          // any series that does not define a rendererIdKey.
          customSeriesRenderers: [
            new charts.LineRendererConfig(
                strokeWidthPx: 2.5,
                dashPattern: [5, 5, 5],
                // ID used to link series to this renderer.
                customRendererId: 'firstLine'),
            new charts.LineRendererConfig(
                strokeWidthPx: 2.5,
                // ID used to link series to this renderer.
                customRendererId: 'secondLine')
          ]),
    );`

And this is the error:

I/flutter ( 4351): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4351): The following assertion was thrown during performLayout():
I/flutter ( 4351): Failed assertion: boolean expression must not be null
I/flutter ( 4351):
I/flutter ( 4351): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4351): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4351): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4351):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 4351):
I/flutter ( 4351): When the exception was thrown, this was the stack:
I/flutter ( 4351): #0      LineRenderer._createLineAndAreaElements (package:charts_common/src/chart/line/line_renderer.dart:629)
I/flutter ( 4351): #1      LineRenderer.update.<anonymous closure>.<anonymous closure> (package:charts_common/src/chart/line/line_renderer.dart:371)
I/flutter ( 4351): #2      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
I/flutter ( 4351): #3      LineRenderer.update.<anonymous closure> (package:charts_common/src/chart/line/line_renderer.dart:359)
I/flutter ( 4351): #4      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:278)
I/flutter ( 4351): #5      LineRenderer.update (package:charts_common/src/chart/line/line_renderer.dart:319)
I/flutter ( 4351): #6      BaseChart.onPostLayout.<anonymous closure> (package:charts_common/src/chart/common/base_chart.dart:515)
I/flutter ( 4351): #7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:370)
I/flutter ( 4351): #8      BaseChart.onPostLayout (package:charts_common/src/chart/common/base_chart.dart:514)
I/flutter ( 4351): #9      CartesianChart.onPostLayout (package:charts_common/src/chart/cartesian/cartesian_chart.dart:381)
I/flutter ( 4351): #10     BaseChart.layout (package:charts_common/src/chart/common/base_chart.dart:314)
I/flutter ( 4351): #11     ChartContainerRenderObject.performLayout (package:charts_flutter/src/chart_container.dart:209)
I/flutter ( 4351): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #17     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142)
I/flutter ( 4351): #18     WidgetLayoutDelegate.performLayout (package:charts_flutter/src/widget_layout_delegate.dart:80)
I/flutter ( 4351): #19     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212)
I/flutter ( 4351): #20     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356)
I/flutter ( 4351): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #22     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258)
I/flutter ( 4351): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #24     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258)
I/flutter ( 4351): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #26     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199)
I/flutter ( 4351): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #28     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738)
I/flutter ( 4351): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #32     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142)
I/flutter ( 4351): #33     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339)
I/flutter ( 4351): #34     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212)
I/flutter ( 4351): #35     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356)
I/flutter ( 4351): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #40     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188)
I/flutter ( 4351): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #42     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385)
I/flutter ( 4351): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #59     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2881)
I/flutter ( 4351): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #61     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510)
I/flutter ( 4351): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #63     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
I/flutter ( 4351): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1634)
I/flutter ( 4351): #73     RenderView.performLayout (package:flutter/src/rendering/view.dart:147)
I/flutter ( 4351): #74     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509)
I/flutter ( 4351): #75     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768)
I/flutter ( 4351): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281)
I/flutter ( 4351): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677)
I/flutter ( 4351): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219)
I/flutter ( 4351): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990)
I/flutter ( 4351): #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930)
I/flutter ( 4351): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751)
I/flutter ( 4351): #83     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382)
I/flutter ( 4351): #84     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416)
I/flutter ( 4351): #85     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171)
I/flutter ( 4351): (elided one frame from package dart:async)
I/flutter ( 4351):
I/flutter ( 4351): The following RenderObject was being processed when the exception was fired:
I/flutter ( 4351):   ChartContainerRenderObject<String>#01080 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4351):   parentData: <none>
I/flutter ( 4351):   constraints: BoxConstraints(w=348.0, h=205.0)
I/flutter ( 4351):   semantic boundary
I/flutter ( 4351):   size: MISSING
I/flutter ( 4351): This RenderObject has no descendants.
I/flutter ( 4351): ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by TomOerlemans** [comment]
So I am far from a great programmer (and thus I don't really understand what is going on), but I just discovered that this issue does not exist when I use charts_flutter: ^0.4.0, as opposed to charts_flutter: ^0.5.0. So it seems like the issue got introduced with the latest update.
