### ISSUE TITLE
breaks on scroll

### ISSUE THREAD

**Issue by ArtificialPenguins** [google/charts#186]
the pie charts break when they're put in a listview and scrolled.
![donutchart](https://user-images.githubusercontent.com/5252797/50061872-8c0e2d80-0158-11e9-9d64-d27b3a07b042.JPG)

**Comment by abolajibisiriyu** [comment]
Hi, I this issue also happens for the line graph on a CustomScrollView.
**Before Scrolled**
![simulator screen shot - iphone 5s - 2019-01-11 at 12 02 22](https://user-images.githubusercontent.com/8493924/51030356-7b0add80-1599-11e9-8672-6f6459808efe.png)

**After Scrolled**
![simulator screen shot - iphone 5s - 2019-01-11 at 12 02 15](https://user-images.githubusercontent.com/8493924/51030395-9970d900-1599-11e9-90c8-67598b9d98d3.png)

**Error:**
`flutter: #51     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
flutter: #52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2088:7)
flutter: #53     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
flutter: #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:122:15)
flutter: #55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2088:7)
flutter: #56     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
flutter: #57     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
flutter: #58     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:855:29)
flutter: #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:283:19)
flutter: #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
flutter: #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #65     _invoke (dart:ui/hooks.dart:154:13)
flutter: #66     _drawFrame (dart:ui/hooks.dart:143:3)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   ChartContainerRenderObject<DateTime>#fa246
flutter:   creator: ChartContainer<DateTime> ← Listener ← _GestureSemantics ← RawGestureDetector ←
flutter:   GestureDetector ← LayoutId-[<chartContainer>] ← CustomMultiChildLayout ← TimeSeriesChart ←
flutter:   ConstrainedBox ← Container ← Flexible ← Column ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=302.0, h=200.0)
flutter:   semantics node: SemanticsNode#52
flutter:   semantic boundary
flutter:   size: Size(302.0, 200.0)
flutter: This RenderObject has no descendants.
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The method 'containsPoint' was called on null.
flutter: Another exception was thrown: 'package:charts_common/src/chart/layout/layout_manager_impl.dart': Failed assertion: line 113 pos 12: '_drawAreaBoundsOutdated == false': is not true.
flutter: Another exception was thrown: 'package:charts_common/src/chart/layout/layout_manager_impl.dart': Failed assertion: line 113 pos 12: '_drawAreaBoundsOutdated == false': is not true.`

**Comment by Robin3D** [comment]
I had the same problem, do you know how to fix it? @ArtificialPenguins

**Comment by ArtificialPenguins** [comment]
@Robin3D I do not. DM me if you find the answer.

**Comment by zykoikaze** [comment]
I met it, too.Does anyone find the answer？
