### ISSUE TITLE
includePoints error on null values in TimeSeriesChart

### ISSUE THREAD

**Issue by luxomansilla** [google/charts#214]
I have an error when i have a TimeSeriesChart with includePoints = true.
The problem is when i have null values.

defaultRenderer: new charts.LineRendererConfig(includePoints: true)

I/flutter (13456): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13456): The following NoSuchMethodError was thrown during performLayout():
I/flutter (13456): The method '+' was called on null.
I/flutter (13456): Receiver: null
I/flutter (13456): Tried calling: +(0)
I/flutter (13456): 
I/flutter (13456): When the exception was thrown, this was the stack:
I/flutter (13456): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (13456): #1      PointRenderer.getPoint 
package:charts_common/…/scatter_plot/point_renderer.dart:443
I/flutter (13456): #2      PointRenderer.update.<anonymous closure> 
package:charts_common/…/scatter_plot/point_renderer.dart:243
I/flutter (13456): #3      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
I/flutter (13456): #4      PointRenderer.update 
package:charts_common/…/scatter_plot/point_renderer.dart:206
I/flutter (13456): #5      LineRenderer.update 
package:charts_common/…/line/line_renderer.dart:536
I/flutter (13456): #6      BaseChart.onPostLayout.<anonymous closure> 
package:charts_common/…/common/base_chart.dart:560
I/flutter (13456): #7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection/runtime/libcompact_hash.dart:367:8)
I/flutter (13456): #8      BaseChart.onPostLayout 
package:charts_common/…/common/base_chart.dart:559
I/flutter (13456): #9      CartesianChart.onPostLayout 
package:charts_common/…/cartesian/cartesian_chart.dart:430
I/flutter (13456): #10     BaseChart.layout 
package:charts_common/…/common/base_chart.dart:374
I/flutter (13456): #11     ChartContainerRenderObject.performLayout 
package:charts_flutter/src/chart_container.dart:215
I/flutter (13456): #12     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (13456): #14     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
I/flutter (13456): #16     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #17     MultiChildLayoutDelegate.layoutChild 
package:flutter/…/rendering/custom_layout.dart:142
I/flutter (13456): #18     WidgetLayoutDelegate.performLayout 
package:charts_flutter/src/widget_layout_delegate.dart:80
I/flutter (13456): #19     MultiChildLayoutDelegate._callPerformLayout 
package:flutter/…/rendering/custom_layout.dart:212
I/flutter (13456): #20     RenderCustomMultiChildLayoutBox.performLayout 
package:flutter/…/rendering/custom_layout.dart:356
I/flutter (13456): #21     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #22     RenderConstrainedBox.performLayout 
package:flutter/…/rendering/proxy_box.dart:259
I/flutter (13456): #23     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #24     RenderFlex.performLayout 
package:flutter/…/rendering/flex.dart:738
I/flutter (13456): #25     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #26     RenderPadding.performLayout 
package:flutter/…/rendering/shifted_box.dart:199
I/flutter (13456): #27     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (13456): #29     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (13456): #31     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (13456): #33     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (13456): #35     _RenderCustomClip.performLayout 
package:flutter/…/rendering/proxy_box.dart:1206
I/flutter (13456): #36     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #37     RenderPadding.performLayout 
package:flutter/…/rendering/shifted_box.dart:199
I/flutter (13456): #38     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (13456): #40     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (13456): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout

**Comment by vladms** [comment]
@luxomansilla Did you find a solution for this?

**Comment by brooth** [comment]
Removing this guy solves the problem:
```
   defaultRenderer: Charts.LineRendererConfig(...),
```

**Comment by micimize** [comment]
adding a non-null default value to `measureFn: (RecordValue record, _) => record.value ?? 0.0` allows points to render, but I have yet to find an actually viable workaround (save for not using `includePoints`)

**Comment by micimize** [comment]
Seems `PointsRenderer.update` just needs [`if (measureValue == null) { continue; }`](https://github.com/micimize/charts/commit/694f73d4290562e274deb2805c001a33bb4748f8)

**Comment by marcoms** [comment]
It would be great if this could be merged upstream, for such a simple fix.
