### ISSUE TITLE
Another exception was thrown: Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by domgolonka** [google/charts#260]
When all the series are 0.0, the chart throws out Infinity or NaN toInt. Just a bug that I saw.

**Comment by Nico04** [comment]
I've got the same issue : if one of the series have only 0.0, it throws.

**Comment by rakakhrl** [comment]
Got the same issue. This shouldn't be an issue right? because sometime the data is 0 but why it's throwing exception

**Comment by Nico04** [comment]
My hack at the time was to manually remove thoses values from data

**Comment by rakakhrl** [comment]
> 
> 
> My hack at the time was to manually remove thoses values from data

Can you explain what do you mean by this?

**Comment by Nico04** [comment]
> 
> 
> > My hack at the time was to manually remove thoses values from data
> 
> Can you explain what do you mean by this?

In my case, zero values where in any case not visible in the graph, so I just filtered the data before giving it to the graph

**Comment by rakakhrl** [comment]
> 
> In my case, zero values where in any case not visible in the graph, so I just filtered the data before giving it to the graph

That's one way to solving the problem but unfortunately in my case i need to show all the data even it have 0 value

**Comment by ProFive** [comment]
The same problem 
`When the exception was thrown, this was the stack
#0      double.toInt  (dart:core-patch/double.dart:193:36)
#1      double.round  (dart:core-patch/double.dart:162:34)
#2      AutoAdjustingDateTimeTickProvider._getClosestTickProvider 
package:charts_common/…/time/auto_adjusting_date_time_tick_provider.dart:140
#3      AutoAdjustingDateTimeTickProvider.getTicks 
package:charts_common/…/time/auto_adjusting_date_time_tick_provider.dart:109
#4      PanningTickProvider.getTicks 
package:charts_common/…/zoom/panning_tick_provider.dart:75
...
Handler: "onUpdate"
Recognizer: ScaleGestureRecognizer#cf2af
    debugOwner: GestureDetector
════════════════════════════════════════════════════════════════════════════════
`
Pro any solution?

**Comment by cuong292** [comment]
same issue. when all is 0.0, it's throw this ugly exception

**Comment by rakakhrl** [comment]
> In my case, zero values where in any case not visible in the graph, so I just filtered the data before giving it to the graph

You can use the solution provided by @Nico04 above if you don't need to show the data with 0 value. 

But if it's a requirement and you absolutely have to you can use another package. In my case i use [flutter_echarts](https://pub.dev/packages/flutter_echarts)
