### ISSUE TITLE
Use Charts Example throw exception

### ISSUE THREAD

**Issue by swillk** [google/charts#29]
This is My Code 
```
@override
  Widget build(BuildContext context) {
    return new Container(
       child: new NonzeroBoundMeasureAxis.withSampleData(),
    );
  }
```

but Console Throw
```
Reloaded 2 of 652 libraries in 1,359ms.
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building RawGestureDetector(state:
RawGestureDetectorState#2cb6d(gestures: [tap])):
type '(MyRow, int) => DateTime' is not a subtype of type '(dynamic, int) => DateTime'
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
#0      new MutableSeries (package:charts_common/src/chart/common/processed_series.dart:54:23)
#1      BaseChart.makeSeries (package:charts_common/src/chart/common/base_chart.dart:337:19)
#2      CartesianChart.makeSeries (package:charts_common/src/chart/cartesian/cartesian_chart.dart:125:35)
#3      BaseChart.draw.<anonymous closure> (package:charts_common/src/chart/common/base_chart.dart:292:49)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#6      new List.from (dart:core/runtime/libarray_patch.dart:51:29)
#7      BaseChart.draw (package:charts_common/src/chart/common/base_chart.dart:291:35)
#8      ChartContainerRenderObject.reconfigure (package:charts_flutter/src/chart_container.dart:109:14)
#9      ChartContainer.createRenderObject (package:charts_flutter/src/chart_container.dart:56:46)
#10     RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4259:28)
#11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4632:11)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#37     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3938:11)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#39     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4738:32)
#40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#60     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#65     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3938:11)
#66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#67     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4738:32)
#68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#85     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#92     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#96     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4633:14)
#97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#100    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#101    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#104    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#109    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:3938:11)
#110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#111    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3636:16)
#113    Element.rebuild (package:flutter/src/widgets/framework.dart:3478:5)
#114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3605:5)
#115    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3752:11)
#116    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3600:5)
#117    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2890:14)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:2693:12)
#119    SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:729:20)
#120    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2205:19)
#121    SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:722:11)
#122    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
#123    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1666:58)
#124    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:740:15)
#125    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1666:13)
#126    RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
#127    RenderSliverMultiBoxAdaptor.insertAndLayoutLeadingChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:382:5)
#128    RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:184:31)
#129    RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
#130    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:285:13)
#131    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1008:12)
#132    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:932:20)
#133    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
#134    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
#135    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
#136    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:622:13)
#137    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
#138    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#139    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#140    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
#141    _invoke (dart:ui/hooks.dart:120:13)
#142    _drawFrame (dart:ui/hooks.dart:109:3)
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: The WidgetLayoutDelegate custom multichild layout delegate forgot to lay out the following child:

```

**Comment by swillk** [comment]
May be the problem caused by modifying the source code, there is no problem to re-add it。
