### ISSUE TITLE
Legend issues

### ISSUE THREAD

**Issue by H25** [google/charts#363]
Issue 1:
=====
When I click on a legend entry for hiding the corresponding series and then click on it again for showing the series it results in an exception: data is null
However, if a series entry is selected before everything works ... 

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building TimeSeriesChart(dirty, dependencies: [_LocalizationsScope-[GlobalKey#502b8], MediaQuery, Directionality, _InheritedTheme, DefaultTextStyle], state: BaseChartState<DateTime>#37cd0(tickers: tracking 1 ticker)):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TimeSeriesChart file:///C:/Users/Hannes/Documents/Projekte/Projekt_Master/App/heating_controller/lib/pages/history.dart:221:27
When the exception was thrown, this was the stack: 
#2      new Text (package:flutter/src/widgets/text.dart:285:10)
#3      SimpleLegendEntryLayout.createMeasureValue (package:charts_flutter/src/behaviors/legend/legend_entry_layout.dart:77:20)
#4      SimpleLegendEntryLayout.build (package:charts_flutter/src/behaviors/legend/legend_entry_layout.dart:93:11)
#5      BaseLegendContentBuilder.build.<anonymous closure> (package:charts_flutter/src/behaviors/legend/legend_content_builder.dart:56:32)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 285 pos 10: 'data != null'
The relevant error-causing widget was: 
  TimeSeriesChart file:///C:/Users/Hannes/Documents/Projekte/Projekt_Master/App/heating_controller/lib/pages/history.dart:221:27

Issue 2:
=====
When a slider is moved to fast and therefore setState() is called in a short time intervall the exception below is thrown. However, if I remove the legend it does not crash.

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'package:charts_common/src/chart/layout/layout_manager_impl.dart': Failed assertion: line 115 pos 12: '_drawAreaBoundsOutdated == false': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TimeSeriesChart file:///C:/Users/Hannes/Documents/Projekte/Projekt_Master/App/heating_controller/lib/pages/history.dart:219:27
When the exception was thrown, this was the stack: 
#2      LayoutManagerImpl.drawableLayoutAreaBounds (package:charts_common/src/chart/layout/layout_manager_impl.dart:115:12)
#3      BaseChart.drawableLayoutAreaBounds (package:charts_common/src/chart/common/base_chart.dart:438:22)
#4      _LinePointLayoutView.paint (package:charts_common/src/chart/common/behavior/line_point_highlighter.dart:418:30)
#5      BaseChart.paint.<anonymous closure> (package:charts_common/src/chart/common/base_chart.dart:603:12)
#6      List.forEach (dart:core-patch/growable_array.dart:285:8)
...
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<DateTime>#aab27
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=328.0, h=270.0)
...  semantic boundary
...  size: Size(328.0, 270.0)
RenderObject: ChartContainerRenderObject<DateTime>#aab27
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=328.0, h=270.0)
  semantic boundary
  size: Size(328.0, 270.0)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
The method 'any' was called on null.
Receiver: null
Tried calling: any(Closure: (LegendEntry<DateTime>) => bool)
The relevant error-causing widget was: 
  TimeSeriesChart file:///C:/Users/Hannes/Documents/Projekte/Projekt_Master/App/heating_controller/lib/pages/history.dart:219:27

Flutter doctor output:
==============
[√] Flutter (Channel beta, v1.12.13+hotfix.3, on Microsoft Windows [Version 10.0.18362.476], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.5)

Code (neccessary stuff only):
=====
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_datetime_picker/flutter_datetime_picker.dart';
import 'package:heating_controller/localization/AppLocalization.dart';
import 'package:heating_controller/utility/constants.dart';
import 'package:intl/intl.dart';
import 'package:charts_flutter/flutter.dart' as charts;
import 'package:progress_dialog/progress_dialog.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:heating_controller/utility/testDataMaker.dart';

class History extends StatefulWidget {

  final Map mInitialValues;

  History({Key key, this.mInitialValues}): super(key: key);

  @override
  State<StatefulWidget> createState() => HistoryState();
}

class HistoryState extends State<History> {

  DateTime _mDateTime;
  static const List<String> _mSteps = ["5min", "15min", "30min", "1h", "2h", "4h"];
  int _mStepSelection = 0;
  static const double CHART_HEIGHT_PORTRAIT = 350;
  static const double CHART_HEIGHT_LANDSCAPE = 300;
  String _mSelectedPeriod;
  static const List<String> _mPeriodList = ["1h", "2h", "4h", "12h", "1d"];
  bool _mAnimate = true;
  bool _demoMode;
  List<charts.Series<TimeSeriesHistory, DateTime>> mChartSeriesList;
  List<String> _mChartDisplayNames;

  @override
  void initState() {
    super.initState();
    _mDateTime = DateTime.now();
    _mSelectedPeriod = "1h";
    _initChart();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _setChartDisplayNames();
      _updateChartData(widget.mInitialValues);
      ;});
  }

  @override
  Widget build(BuildContext context) {
    _buildProgressDialog();
    final String title = AppLocalizations.of(context).history;
    return new Scaffold(
        appBar: AppBar(title: Text(title)),
        body: SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Padding(
            padding: EdgeInsets.only(left: 16.0, right: 16.0),
            child: Column(
              children: <Widget>[
                _buildSelectionStuff(),
                _buildChart()
              ]
            ),
          ),
        )
    );
  }

  /// contains the button for picking the start date, the dropdown for selecting
  /// the period and the slider for setting the step size
  Widget _buildSelectionStuff() {
    return Column(
      children: <Widget>[
        Row(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Padding(
              padding: EdgeInsets.only(right: 2),
              child: Text(AppLocalizations.of(context).date),
            ),
            FlatButton(
              child: Text(_formatDate(_mDateTime), style: TextStyle(fontWeight: FontWeight.bold),),
              textColor: Theme.of(context).primaryColor,
              onPressed: () {
                _showDatePicker();
              },
            )
          ],
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Padding(
              padding: EdgeInsets.only(right: 20),
              child: Text(AppLocalizations.of(context).period),
            ),
            DropdownButton<String>(
              value: _mSelectedPeriod,
              icon: Icon(Icons.arrow_drop_down),
              iconSize: 24,
              elevation: 8,
              style: TextStyle(
                  color: Theme.of(context).primaryColor,
                  fontWeight: FontWeight.bold
              ),
              onChanged: (String newValue) {
                setState(() {
                  _mSelectedPeriod = newValue;
                  _mStepSelection = 0;
                });
              },
              items: _mPeriodList.map<DropdownMenuItem<String>>((String value) {
                return DropdownMenuItem<String>(
                  value: value,
                  child: Text(value),
                );
              }).toList(),
            )
          ],
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            Padding(
              padding: EdgeInsets.only(right: 2),
              child: Text(AppLocalizations.of(context).stepSize),
            ),
            Slider(
              max: _getMaxStep(),
              min: 0.0,
              divisions: _getDivisionStep(),
              value: _mStepSelection.toDouble(),
              activeColor: Theme.of(context).primaryColor,
              onChanged: (value) {
                setState(() {
                  _mStepSelection = value.toInt();
                });
              },
              label: _mSteps[_mStepSelection],
            ),
            Text(_mSteps[_mStepSelection], style: TextStyle(fontWeight: FontWeight.bold, color: Theme.of(context).primaryColor))
          ],
        )
      ],
    );
  }

  Widget _buildChart() {
    /// different layout in portrait and landscape mode
    if (MediaQuery.of(context).orientation == Orientation.portrait) {
      List<charts.ChartBehavior> behaviors = [charts.SeriesLegend(
        position: charts.BehaviorPosition.top,
        horizontalFirst: true,
        desiredMaxColumns: 2,
        cellPadding: new EdgeInsets.only(right: 8.0, bottom: 4.0),
        showMeasures: true,
        legendDefaultMeasure: charts.LegendDefaultMeasure.firstValue,
        measureFormatter: (num value) {
          return value == null ? '-' : value.toInt().toString() + "°C";
        },
      )];
      return _buildChartWidget(CHART_HEIGHT_PORTRAIT, behaviors);
    } else {
      List<charts.ChartBehavior> behaviors = [charts.SeriesLegend(
        position: charts.BehaviorPosition.top,
        horizontalFirst: true,
        desiredMaxColumns: 4,
        cellPadding: new EdgeInsets.only(right: 8.0, bottom: 4.0),
        showMeasures: true,
        legendDefaultMeasure: charts.LegendDefaultMeasure.firstValue,
        measureFormatter: (num value) {
          return value == null ? '-' : value.toInt().toString() + "°C";
        },
      )];
      return _buildChartWidget(CHART_HEIGHT_LANDSCAPE, behaviors);
    }
  }

  Widget _buildChartWidget(double height, List<charts.ChartBehavior> behaviors) {
    return Padding(
        padding: EdgeInsets.only(bottom: 4),
        child: Container(
            height: height,
            width: MediaQuery.of(context).size.width,
            child: charts.TimeSeriesChart(
              mChartSeriesList,
              animate: _mAnimate,
              domainAxis: _getDomainAxisSpec(),
              primaryMeasureAxis: _getPrimaryAxisSpec(),
              behaviors: behaviors,
            )
        )
    );
  }

  charts.NumericAxisSpec _getPrimaryAxisSpec() {
    return charts.NumericAxisSpec(
        tickFormatterSpec: charts.BasicNumericTickFormatterSpec((num value) {
          return (value!=null ? value.toInt().toString() + "°C" : "");
        })
    );
  }

  charts.DateTimeAxisSpec _getDomainAxisSpec() {
    return charts.DateTimeAxisSpec(
        tickFormatterSpec: charts.AutoDateTimeTickFormatterSpec(
          minute: charts.TimeFormatterSpec(format: 'HH:mm', transitionFormat: "HH:mm", noonFormat: "HH:mm"),
          hour: charts.TimeFormatterSpec(format: 'HH:mm', transitionFormat: "HH:mm", noonFormat: "HH:mm"),
          day: charts.TimeFormatterSpec(format: 'dd.', transitionFormat: "dd.MM", noonFormat: "dd.MM"),
        )
    );
  }

  /// called when user wants new data
  Future<Map> _getChartData() {
    /// transform period to minutes
    int period = 0;
    switch(_mSelectedPeriod) {
      case "1h": period = 60; break;
      case "2h": period = 60*2; break;
      case "4h": period = 60*4; break;
      case "12h": period = 60*12; break;
      case "1d": period = 60*24; break;
      default: period = 60; break;
    }
    /// transform period to minutes
    int step = 0;
    switch(_mStepSelection) {
      case 0: step = 5; break;
      case 1: step = 15; break;
      case 2: step = 30; break;
      case 3: step = 60; break;
      case 4: step = 120; break;
      case 5: step = 240; break;
      default: step = 5; break;
    }
    if (_demoMode) {
      return TestDataMaker.getRandomHistoryDataDelayed(2, _mDateTime, step, period);
    } else {
      // TODO: get data from server
    }
  }

  /// init the chart with the values from the main page which are passed via
  /// the constructor. If they are null zero will be taken as value
  void _initChart() {
    /// init list
    mChartSeriesList = List(NUMBER_OF_DISPLAYED_VALUES);
    /// generate init data
    List<List<TimeSeriesHistory>> initValues;
    if (widget.mInitialValues != null) {
      initValues = [
        widget.mInitialValues[KEY_MAP_TEMP_PIPE],
        widget.mInitialValues[KEY_MAP_TEMP_SUPPLY],
        widget.mInitialValues[KEY_MAP_TEMP_BOILER],
        widget.mInitialValues[KEY_MAP_TEMP_P1],
        widget.mInitialValues[KEY_MAP_TEMP_P2],
        widget.mInitialValues[KEY_MAP_TEMP_P3],
        widget.mInitialValues[KEY_MAP_TEMP_P4]
      ];
    } else {
      DateTime currentTime = DateTime.now();
      initValues = [
        [TimeSeriesHistory(timeCurrent: currentTime, value: 0)],
        [TimeSeriesHistory(timeCurrent: currentTime, value: 0)],
        [TimeSeriesHistory(timeCurrent: currentTime, value: 0)],
        [TimeSeriesHistory(timeCurrent: currentTime, value: 0)],
        [TimeSeriesHistory(timeCurrent: currentTime, value: 0)],
        [TimeSeriesHistory(timeCurrent: currentTime, value: 0)],
        [TimeSeriesHistory(timeCurrent: currentTime, value: 0)]
      ];
    }
    /// add chart series to list
    for (int i=0; i<NUMBER_OF_DISPLAYED_VALUES; i++) {
      mChartSeriesList[i] = _createSeriesListEntry(
          mappedChartsStyling[i][KEY_MAP_ID],
          mappedChartsStyling[i][KEY_MAP_COLOR],
          initValues[i]);
    }
  }

  /// update the chart
  /// values of the [map] = List<TimeSeriesHistory>
  Future<void> _updateChartData(Map map) async {
    List<List<TimeSeriesHistory>> data = [
      map[KEY_MAP_TEMP_PIPE],
      map[KEY_MAP_TEMP_SUPPLY],
      map[KEY_MAP_TEMP_BOILER],
      map[KEY_MAP_TEMP_P1],
      map[KEY_MAP_TEMP_P2],
      map[KEY_MAP_TEMP_P3],
      map[KEY_MAP_TEMP_P4]
    ];
    setState(() {
      /// reset list
      mChartSeriesList = List(NUMBER_OF_DISPLAYED_VALUES);
      /// add new values
      for (int i=0; i<NUMBER_OF_DISPLAYED_VALUES; i++) {
        mChartSeriesList[i] = _createSeriesListEntry(
            mappedChartsStyling[i][KEY_MAP_ID],
            mappedChartsStyling[i][KEY_MAP_COLOR],
            data[i],
            displayName: _mChartDisplayNames[i]);
      }
    });
    return null;
  }

  /// Creates a chart series
  /// Define the line color with [color]
  /// [data] is a list of values: x-axis = time, y-axis = temp or state
  /// The [displayName] parameter is optional, default = ""
  charts.Series<TimeSeriesHistory, DateTime> _createSeriesListEntry(
      String id,
      charts.Color color,
      List<TimeSeriesHistory> data,
      {String displayName=""}) {
    return charts.Series<TimeSeriesHistory, DateTime>(
      id: id,
      colorFn: (_, __) => color,
      domainFn: (TimeSeriesHistory value, _) => value.timeCurrent,
      measureFn: (TimeSeriesHistory value, _) => value.value,
      data: data,
      displayName: displayName
    );
  }

  /// display name = name of series in legend
  /// needs to be called after widgets are build and build context is valid
  _setChartDisplayNames() {
    AppLocalizations appLocalizations = AppLocalizations.of(context);
    _mChartDisplayNames = [
      appLocalizations.pipe,
      appLocalizations.supply,
      appLocalizations.boiler,
      appLocalizations.p1,
      appLocalizations.p2,
      appLocalizations.p3,
      appLocalizations.p4
    ];
  }
}

class TimeSeriesHistory {
  final DateTime timeCurrent;
  final int value;

  TimeSeriesHistory({this.timeCurrent, this.value});
}
```

**Comment by H25** [comment]
issue 1 does not appear in a release build

**Comment by dennis-szymanski** [comment]
I can confirm issue 1. And I can confirm that it doesn't appear in a release build. Is there any solution?

**Comment by johnatdoshii** [comment]
Re: Issue 1 - we are experiencing the same issue. Is there a work-around for this?
