### ISSUE TITLE
Pie chart + widget rebuild when callback on click of a segment breaks if clicked repeatedly

### ISSUE THREAD

**Issue by harrisbaitalrayan** [google/charts#425]
Have a pie chart on which select callback is used using selectionModels. On the updatedListener , a method is called which redraws the widget. If the click is done repeatedly ( somewhat faster ) the pie breaks with following exception.

flutter: The following NoSuchMethodError was thrown while handling a gesture:
flutter: The method 'containsPoint' was called on null.
flutter: Receiver: null
flutter: Tried calling: containsPoint(Instance of 'Point<double>')
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
flutter: #1      BaseChart.pointWithinRenderer.<anonymous closure> (package:charts_common/src/chart/common/base_chart.dart:211:14)
flutter: #2      SetMixin.any (dart:collection/set.dart:196:15)
flutter: #3      BaseChart.pointWithinRenderer (package:charts_common/src/chart/common/base_chart.dart:208:28)
flutter: #4      SelectNearest._onTapTest (package:charts_common/src/chart/common/behavior/selection/select_nearest.dart:156:19)
flutter: #5      ProxyGestureListener._populateActiveListeners.<anonymous closure> (package:charts_common/src/common/proxy_gesture_listener.dart:131:30)
flutter: #6      List.forEach (dart:core-patch/growable_array.dart:282:8)
flutter: #7      ProxyGestureListener._populateActiveListeners (package:charts_common/src/common/proxy_gesture_listener.dart:130:20)
flutter: #8      ProxyGestureListener.onTapTest (package:charts_common/src/common/proxy_gesture_listener.dart:37:12)

**Comment by harrisbaitalrayan** [comment]
I think the issue is when repeatedly clicking, a click occurs when widget tree redraw is still in progress which breaks.

**Comment by harrisbaitalrayan** [comment]
Hi, is there an update on this ?
