### ISSUE TITLE
PieChart not working in latest Flutter

### ISSUE THREAD

**Issue by elogic2square** [google/charts#660]
The relevant error-causing widget was: 
  PieChart<dynamic> file:///home/user/Flutter_Samples/18JUL/charts-master/charts_flutter/example/lib/pie_chart/auto_label.dart:73:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1930:12)
#3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:27)
#4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
...
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<dynamic>#8e28a
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=368.0, h=250.0)
...  semantic boundary
...  size: MISSING
RenderObject: ChartContainerRenderObject<dynamic>#8e28a
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=368.0, h=250.0)
  semantic boundary
  size: MISSING

**Comment by richardscollin** [comment]
I encountered this same issue as well.

It seems the issue occurs when you use the `defaultRenderer` parameter.

You don't encounter the issue if you construct the pie chart like this:
```
charts.PieChart(
      seriesList,
      animate: animate,
    )
```

**Comment by habibrosyad** [comment]
I encountered this issue only when building a release (just blank space), on debug it's fine. Weird.

**Comment by habibrosyad** [comment]
There's a workaround for this issue in https://github.com/google/charts/issues/651#issuecomment-876019043, and I think we can close this one in favor of https://github.com/google/charts/issues/651.
