### ISSUE TITLE
donut chart error size MISSING

### ISSUE THREAD

**Issue by eggysudianto** [google/charts#730]
```
defaultRenderer: charts.ArcRendererConfig(
                        arcRendererDecorators: [
                          new charts.ArcLabelDecorator(
                              labelPosition: charts.ArcLabelPosition.inside,
                              insideLabelStyleSpec: new charts.TextStyleSpec(fontSize: 16, color:
                              charts.Color.fromHex(code: "#FFFFFF")))
                        ])
```

after I add above code to pie chart then the pie chart is not show anymore with error log 

```
The relevant error-causing widget was: 
  PieChart<dynamic> PieChart:file:///D:/ANDROID/lib/DonutAutoLabelChart.dart:73:16
When the exception was thrown, this was the stack: 
#2      RenderBox.size (package:flutter/src/rendering/box.dart:1927:12)
#3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:27)
#4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#7      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#13     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2792:15)
#14     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
#15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#20     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2792:15)
#21     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
#22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#24     RenderSliverSingleBoxAdapter.paint (package:flutter/src/rendering/sliver.dart:1779:15)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#27     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:660:17)
#28     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:392:12)
#29     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:448:7)
#30     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:635:38)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
#32     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#33     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#34     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:973:29)
#35     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499:19)
#36     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#37     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#38     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#39     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#40     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#44     _invoke (dart:ui/hooks.dart:150:10)
#45     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#46     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 5 frames from class _AssertionError and dart:async)
The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<dynamic>#42d40
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=600.9, h=250.0)
...  semantic boundary
...  size: MISSING
RenderObject: ChartContainerRenderObject<dynamic>#42d40
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=600.9, h=250.0)
  semantic boundary
  size: MISSING
```

I try to download this repo on github and I build, have same result donut chart from this repo is not show with same error with mine.

please fix this

**Comment by AgustinDipolito** [comment]
Same here, any update?

**Comment by codexcer** [comment]
I'm glad im not the only one having issue with this haha

**Comment by Andresit0** [comment]
same problem :/

**Comment by yuenzp** [comment]
give a type to the pie chart, it will solve the problem

`new charts.PieChart<int>()`

> ```
> defaultRenderer: charts.ArcRendererConfig(
>                         arcRendererDecorators: [
>                           new charts.ArcLabelDecorator(
>                               labelPosition: charts.ArcLabelPosition.inside,
>                               insideLabelStyleSpec: new charts.TextStyleSpec(fontSize: 16, color:
>                               charts.Color.fromHex(code: "#FFFFFF")))
>                         ])
> ```
> 
> after I add above code to pie chart then the pie chart is not show anymore with error log
> 
> ```
> The relevant error-causing widget was: 
>   PieChart<dynamic> PieChart:file:///D:/ANDROID/lib/DonutAutoLabelChart.dart:73:16
> When the exception was thrown, this was the stack: 
> #2      RenderBox.size (package:flutter/src/rendering/box.dart:1927:12)
> #3      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:563:27)
> #4      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:605:7)
> #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
> #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
> #7      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
> #8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
> #9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
> #10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
> #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
> #12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
> #13     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2792:15)
> #14     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:408:5)
> #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
> #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
> #17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
> #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
> #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
> #20     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2792:15)
> #21     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1078:7)
> #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
> #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
> #24     RenderSliverSingleBoxAdapter.paint (package:flutter/src/rendering/sliver.dart:1779:15)
> #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
> #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
> #27     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:660:17)
> #28     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:392:12)
> #29     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:448:7)
> #30     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:635:38)
> #31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2403:7)
> #32     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
> #33     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
> #34     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:973:29)
> #35     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:499:19)
> #36     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
> #37     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
> #38     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
> #39     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
> #40     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
> #44     _invoke (dart:ui/hooks.dart:150:10)
> #45     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
> #46     _drawFrame (dart:ui/hooks.dart:114:31)
> (elided 5 frames from class _AssertionError and dart:async)
> The following RenderObject was being processed when the exception was fired: ChartContainerRenderObject<dynamic>#42d40
> ...  parentData: <none> (can use size)
> ...  constraints: BoxConstraints(w=600.9, h=250.0)
> ...  semantic boundary
> ...  size: MISSING
> RenderObject: ChartContainerRenderObject<dynamic>#42d40
>   parentData: <none> (can use size)
>   constraints: BoxConstraints(w=600.9, h=250.0)
>   semantic boundary
>   size: MISSING
> ```
> 
> I try to download this repo on github and I build, have same result donut chart from this repo is not show with same error with mine.
> 
> please fix this

Give a type to the pie chart, it will solve the problem.

`new charts.PieChart<int>()`
